// Auth
export const SET_IS_AUTH_LOADING = 'SET_IS_AUTH_LOADING';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const LOGIN_USER = 'LOGIN_USER';

// Posts
export const SET_IS_HOME_LOADING = 'SET_IS_HOME_LOADING';
export const SET_IS_POST_DETAILS_LOADING = 'SET_IS_POST_DETAILS_LOADING';
export const SET_IS_ADD_POST_LOADING = 'SET_IS_ADD_POST_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_MORE_POSTS = 'GET_MORE_POSTS';
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
export const GET_MORE_POST_COMMENTS = 'GET_POST_COMMENTS';
export const SET_POSTS_CURRENT_PAGE = 'SET_POSTS_CURRENT_PAGE';
export const SET_POSTS_MAX_PAGES = 'SET_POSTS_MAX_PAGES';
export const SET_POST_COMMENTS_CURRENT_PAGE = 'SET_POST_COMMENTS_CURRENT_PAGE';
export const SET_POST_COMMENTS_MAX_PAGES = 'SET_POST_COMMENTS_MAX_PAGES';
