// Auth
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const LOGIN_USER = 'LOGIN_USER';

// Posts
// export const GET_PAGINATED_POSTS = 'GET_PAGINATED_POSTS';
export const SET_IS_HOME_LOADING = 'SET_IS_HOME_LOADING';
export const SET_IS_POST_DETAILS_LOADING = 'SET_IS_POST_DETAILS_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_MORE_POSTS = 'GET_MORE_POSTS';
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
export const SET_POSTS_CURRENT_PAGE = 'SET_POSTS_CURRENT_PAGE';
